name: Auto Login

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

# Environment variables
env:
  # Default credentials (can be overridden by GitHub Secrets)
  FOTTYY_USERNAME: ${{ secrets.FOTTYY_USERNAME || 'nihar' }}
  FOTTYY_PASSWORD: ${{ secrets.FOTTYY_PASSWORD || 'nihar1234' }}

jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libnspr4 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libatspi2.0-0 \
            libxshmfence1 \
            libx11-xcb1
            
      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright
        run: |
          pip install playwright
          # Install browsers with dependencies
          python -m playwright install --with-deps chromium
          python -m playwright install-deps
      
      - name: Run login script
        run: |
          # Set display for headless mode
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 > /dev/null 2>&1 &
          
          # Run the script with retry logic
          max_retries=3
          attempt=1
          success=false
          
          while [ $attempt -le $max_retries ] && [ "$success" = false ]; do
            echo "Attempt $attempt of $max_retries..."
            if python login_script.py; then
              success=true
              echo "Script completed successfully on attempt $attempt"
            else
              echo "Attempt $attempt failed. Retrying..."
              ((attempt++))
              sleep 10  # Wait before retry
            fi
          done
          
          if [ "$success" = false ]; then
            echo "Script failed after $max_retries attempts"
            exit 1
          fi
        timeout-minutes: 20
        env:
          FOTTYY_USERNAME: ${{ env.FOTTYY_USERNAME }}
          FOTTYY_PASSWORD: ${{ env.FOTTYY_PASSWORD }}
        
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: login-script-logs
          path: |
            *.log
            *.txt
            playwright-report/
          retention-days: 3
          if-no-files-found: warn

